name: authentication
description: "Project that consists of registration and registration, in order to use them in your own projects"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.2
  shared_preferences: ^2.2.2
  flutter_verification_code_field: ^1.0.4
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  web_socket_channel: ^2.4.5
  dropdown_button2: ^2.3.9
  sizer: ^2.0.15
  google_nav_bar: ^5.0.6
  flutter_portal: ^1.1.4
  image_picker: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
